# Generated by Django 4.1.4 on 2022-12-27 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="homePageData",
        ),
    ]
