# Generated by Django 4.1.4 on 2022-12-30 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("homepage", "0002_delete_homepagedata"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subscriber",
            fields=[
                ("email_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("email", models.EmailField(max_length=254)),
            ],
        ),
    ]
