# Generated by Django 4.1.4 on 2022-12-14 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stories',
            fields=[
                ('story_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pub_date', models.DateTimeField(verbose_name='Date Published')),
                ('story_title', models.CharField(max_length=200)),
                ('story', models.TextField()),
                ('story_gist', models.CharField(max_length=600)),
                ('story_author', models.CharField(choices=[('Sushma Kanugo', 'Sonu'), ('Unknown', 'Misc')], default='Sushma Kanugo', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StoryLinks',
            fields=[
                ('link_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('link', models.CharField(max_length=200)),
                ('link_type', models.IntegerField(choices=[(1, 'Image'), (2, 'Video')], default=1)),
                ('link_name', models.CharField(max_length=100)),
                ('story_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bloglist.stories')),
            ],
        ),
    ]
