# Generated by Django 4.1.4 on 2022-12-23 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Stories",
            fields=[
                ("story_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("pub_date", models.DateTimeField(verbose_name="Date Published")),
                ("story_title", models.CharField(max_length=200)),
                ("story", models.TextField()),
                ("story_gist", models.CharField(max_length=600)),
                (
                    "story_author",
                    models.CharField(
                        choices=[("Sushma Kanugo", "Sonu"), ("Unknown", "Misc")],
                        default="Sushma Kanugo",
                        max_length=100,
                    ),
                ),
                (
                    "chapter_id",
                    models.IntegerField(
                        default=-1,
                        help_text="Put chapter ID 1 if the story will have chapters else leave it as it is",
                    ),
                ),
                (
                    "genre",
                    models.CharField(
                        choices=[
                            ("Horror", "Horror"),
                            ("Romance", "Romance"),
                            ("Comedy", "Comedy"),
                            ("Drama", "Drama"),
                        ],
                        default="Drama",
                        max_length=100,
                    ),
                ),
                (
                    "story_chapter_link_id",
                    models.IntegerField(
                        default=-1,
                        help_text="Id of the story to which the Chapter is linked?",
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        choices=[(0, "Low"), (1, "Normal"), (2, "High")], default=1
                    ),
                ),
            ],
        ),
    ]
