# Generated by Django 4.1.4 on 2022-12-20 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloglist', '0002_storylinks_image_file_alter_storylinks_link_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storylinks',
            name='image_file',
            field=models.ImageField(blank=True, upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='storylinks',
            name='link_name',
            field=models.URLField(blank=True),
        ),
    ]
