# Generated by Django 4.1.4 on 2022-12-20 10:05

import bloglist.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloglist', '0003_alter_storylinks_image_file_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storylinks',
            old_name='link',
            new_name='object_name',
        ),
        migrations.AlterField(
            model_name='storylinks',
            name='image_file',
            field=models.ImageField(blank=True, upload_to=bloglist.models.content_file_name),
        ),
    ]
