# Generated by Django 4.1.4 on 2022-12-20 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloglist', '0004_rename_link_storylinks_object_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stories',
            name='chapter_id',
            field=models.IntegerField(blank=True, default=1, help_text='Put chapter ID 1 if the story will have chapters else leave it blank'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stories',
            name='story_link_id',
            field=models.IntegerField(blank=True, default=0, help_text='Id of the story to which the Chapter is?'),
            preserve_default=False,
        ),
    ]
