# Generated by Django 4.1.4 on 2022-12-20 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloglist', '0006_alter_stories_chapter_id_alter_stories_story_link_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stories',
            name='story_link_id',
        ),
        migrations.AddField(
            model_name='stories',
            name='story_chapter_link_id',
            field=models.IntegerField(default=-1, help_text='Id of the story to which the Chapter is linked?'),
        ),
        migrations.AlterField(
            model_name='stories',
            name='chapter_id',
            field=models.IntegerField(default=-1, help_text='Put chapter ID 1 if the story will have chapters else leave it as it is'),
        ),
    ]
