# Generated by Django 4.1.4 on 2022-12-20 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloglist', '0007_remove_stories_story_link_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storylinks',
            old_name='link_name',
            new_name='url_link',
        ),
    ]
