# Generated by Django 4.1.4 on 2022-12-20 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bloglist", "0008_rename_link_name_storylinks_url_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="stories",
            name="rating",
            field=models.PositiveIntegerField(
                choices=[(0, "Low"), (1, "Normal"), (2, "High")], default=1
            ),
        ),
    ]
