# Generated by Django 4.1.4 on 2022-12-20 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bloglist", "0009_stories_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stories",
            name="rating",
            field=models.IntegerField(
                choices=[(0, "Low"), (1, "Normal"), (2, "High")], default=1
            ),
        ),
    ]
