# Generated by Django 4.1.4 on 2022-12-20 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bloglist", "0010_alter_stories_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="stories",
            name="genre",
            field=models.CharField(
                choices=[
                    ("Horror", "Horror"),
                    ("Romance", "Romance"),
                    ("Comedy", "Comedy"),
                    ("Drama", "Drama"),
                ],
                default="Drama",
                max_length=100,
            ),
        ),
    ]
